// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtmBC_dgO7HgpTIi7P_aY09OmVun-5HxI',
    appId: '1:144249671417:web:8bcf499f6038cb3acd1c28',
    messagingSenderId: '144249671417',
    projectId: 'flutterauth-f9b92',
    authDomain: 'flutterauth-f9b92.firebaseapp.com',
    storageBucket: 'flutterauth-f9b92.appspot.com',
    measurementId: 'G-DJ8RL3BYMK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzc1Zh2n_W6iaJbi03KI5IYK7Z2v1YE2Q',
    appId: '1:144249671417:android:c94ba9d9a33ff938cd1c28',
    messagingSenderId: '144249671417',
    projectId: 'flutterauth-f9b92',
    storageBucket: 'flutterauth-f9b92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBtYRE0PAiiOwC0s7Lb0srrH0P61ZoWlA',
    appId: '1:144249671417:ios:7bf7d2c41cd8ae90cd1c28',
    messagingSenderId: '144249671417',
    projectId: 'flutterauth-f9b92',
    storageBucket: 'flutterauth-f9b92.appspot.com',
    iosBundleId: 'com.example.onborading',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBtYRE0PAiiOwC0s7Lb0srrH0P61ZoWlA',
    appId: '1:144249671417:ios:85109248c5231550cd1c28',
    messagingSenderId: '144249671417',
    projectId: 'flutterauth-f9b92',
    storageBucket: 'flutterauth-f9b92.appspot.com',
    iosBundleId: 'com.example.onborading.RunnerTests',
  );
}
